# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 486)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-hp-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"background: #00a8f3;;\n"
"color: #ffffff;\n"
"}\n"
"QPushButton {\n"
"background: transparent;\n"
"border: none;\n"
"padding: 9px;\n"
"font: 16pt \"Roboto\";\n"
"}\n"
"QLabel {\n"
"    font: 16pt \"Roboto\";\n"
"}\n"
"QLineEdit {\n"
"padding: 10px;\n"
"font: 16pt \"Roboto\";\n"
"border: 5px solid #fff;\n"
"}\n"
"\n"
"\n"
"#extraRightBox QLineEdit {\n"
"border: 1px solid grey;\n"
"color: grey;\n"
"color: #bababa;\n"
"padding: 5px;\n"
"font: 12pt \"Roboto\";\n"
"}\n"
"#extraRightBox QLabel {\n"
"font: 11pt \"Roboto\";\n"
"margin: 10px;\n"
"}\n"
"#extraRightBox QSpinBox {\n"
"border: 1px solid grey;\n"
"color: #bababa;\n"
"padding: 5px;\n"
"font: 12pt \"Roboto\";\n"
"}\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #00a8f3;\n"
"    height: 8px;\n"
"    margin: 0px 15px 0 15px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #00a8f3;\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #00a8f3;\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background:#00a8f3;\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.extraLeftBox = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extraLeftBox.sizePolicy().hasHeightForWidth())
        self.extraLeftBox.setSizePolicy(sizePolicy)
        self.extraLeftBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraLeftBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraLeftBox.setStyleSheet("background-color:#222327;")
        self.extraLeftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraLeftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraLeftBox.setObjectName("extraLeftBox")
        self.extraColumLayoutLeft = QtWidgets.QVBoxLayout(self.extraLeftBox)
        self.extraColumLayoutLeft.setContentsMargins(0, 0, 0, 0)
        self.extraColumLayoutLeft.setSpacing(0)
        self.extraColumLayoutLeft.setObjectName("extraColumLayoutLeft")
        self.extraContent_2 = QtWidgets.QFrame(self.extraLeftBox)
        self.extraContent_2.setMinimumSize(QtCore.QSize(0, 0))
        self.extraContent_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraContent_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraContent_2.setObjectName("extraContent_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.extraContent_2)
        self.verticalLayout.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.helpText = QtWidgets.QTextEdit(self.extraContent_2)
        self.helpText.setObjectName("helpText")
        self.verticalLayout.addWidget(self.helpText)
        self.extraColumLayoutLeft.addWidget(self.extraContent_2)
        self.gridLayout_2.addWidget(self.extraLeftBox, 1, 0, 1, 1)
        self.contentFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentFrame.sizePolicy().hasHeightForWidth())
        self.contentFrame.setSizePolicy(sizePolicy)
        self.contentFrame.setStyleSheet("background: #222327")
        self.contentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentFrame.setObjectName("contentFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentFrame)
        self.verticalLayout_2.setContentsMargins(9, 30, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.contentFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.licenseInput = QtWidgets.QLineEdit(self.contentFrame)
        self.licenseInput.setMinimumSize(QtCore.QSize(350, 0))
        self.licenseInput.setText("")
        self.licenseInput.setObjectName("licenseInput")
        self.verticalLayout_2.addWidget(self.licenseInput, 0, QtCore.Qt.AlignHCenter)
        self.statusLabel = QtWidgets.QLabel(self.contentFrame)
        self.statusLabel.setStyleSheet("color: #fc832b; font: 12pt;")
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_2.addWidget(self.statusLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.contentFrame, 1, 1, 1, 1)
        self.extraRightBox = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extraRightBox.sizePolicy().hasHeightForWidth())
        self.extraRightBox.setSizePolicy(sizePolicy)
        self.extraRightBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraRightBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraRightBox.setStyleSheet("background-color:#222327;")
        self.extraRightBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraRightBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraRightBox.setObjectName("extraRightBox")
        self.extraColumLayout = QtWidgets.QVBoxLayout(self.extraRightBox)
        self.extraColumLayout.setContentsMargins(0, 0, 0, 0)
        self.extraColumLayout.setSpacing(0)
        self.extraColumLayout.setObjectName("extraColumLayout")
        self.extraContent = QtWidgets.QFrame(self.extraRightBox)
        self.extraContent.setMinimumSize(QtCore.QSize(0, 0))
        self.extraContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraContent.setObjectName("extraContent")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.extraContent)
        self.verticalLayout_3.setContentsMargins(0, 10, 5, -1)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settingsLabel = QtWidgets.QLabel(self.extraContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsLabel.sizePolicy().hasHeightForWidth())
        self.settingsLabel.setSizePolicy(sizePolicy)
        self.settingsLabel.setStyleSheet("font: 16pt")
        self.settingsLabel.setObjectName("settingsLabel")
        self.verticalLayout_3.addWidget(self.settingsLabel)
        self.settingsFrame = QtWidgets.QFrame(self.extraContent)
        self.settingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsFrame.setObjectName("settingsFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.settingsFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.settingsFrame)
        self.scrollArea.setStyleSheet("QFrame {\n"
"border: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -233, 205, 442))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.fibHotKeyInput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fibHotKeyInput.setObjectName("fibHotKeyInput")
        self.gridLayout.addWidget(self.fibHotKeyInput, 7, 1, 1, 1)
        self.hideDrawingsHotKeyInput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.hideDrawingsHotKeyInput.setObjectName("hideDrawingsHotKeyInput")
        self.gridLayout.addWidget(self.hideDrawingsHotKeyInput, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.waitValueSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.waitValueSpinBox.setObjectName("waitValueSpinBox")
        self.gridLayout.addWidget(self.waitValueSpinBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sizeOfSquareSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.sizeOfSquareSpinBox.setProperty("value", 99)
        self.sizeOfSquareSpinBox.setObjectName("sizeOfSquareSpinBox")
        self.gridLayout.addWidget(self.sizeOfSquareSpinBox, 1, 1, 1, 1)
        self.horizontalLineHotKeyInput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.horizontalLineHotKeyInput.setObjectName("horizontalLineHotKeyInput")
        self.gridLayout.addWidget(self.horizontalLineHotKeyInput, 5, 1, 1, 1)
        self.appNameInput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appNameInput.sizePolicy().hasHeightForWidth())
        self.appNameInput.setSizePolicy(sizePolicy)
        self.appNameInput.setObjectName("appNameInput")
        self.gridLayout.addWidget(self.appNameInput, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.trendLineHotKeyInput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.trendLineHotKeyInput.setObjectName("trendLineHotKeyInput")
        self.gridLayout.addWidget(self.trendLineHotKeyInput, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.appShortcutLink = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.appShortcutLink.setText("")
        self.appShortcutLink.setObjectName("appShortcutLink")
        self.gridLayout.addWidget(self.appShortcutLink, 3, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout_3.addWidget(self.settingsFrame)
        self.updateButton = QtWidgets.QPushButton(self.extraContent)
        self.updateButton.setStyleSheet("#updateButton {\n"
"background-color: #00a8f3;\n"
"padding: 5px 20px;\n"
"border: 2px solid #00a8f3;\n"
"font: 12pt \"Roboto\";\n"
"}\n"
"#updateButton:pressed {\n"
"background-color: #2596be;\n"
"}")
        self.updateButton.setObjectName("updateButton")
        self.verticalLayout_3.addWidget(self.updateButton, 0, QtCore.Qt.AlignHCenter)
        self.resetButton = QtWidgets.QPushButton(self.extraContent)
        self.resetButton.setStyleSheet("#resetButton {\n"
"background-color: none;\n"
"padding: 5px 20px;\n"
"border: 2px solid #00a8f3;\n"
"font: 12pt \"Roboto\";}\n"
"#resetButton:pressed {\n"
"border: 2px solid #d5d4d2;\n"
"}")
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout_3.addWidget(self.resetButton, 0, QtCore.Qt.AlignHCenter)
        self.settingsStatusLabel = QtWidgets.QLabel(self.extraContent)
        self.settingsStatusLabel.setText("")
        self.settingsStatusLabel.setObjectName("settingsStatusLabel")
        self.verticalLayout_3.addWidget(self.settingsStatusLabel)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 10)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 1)
        self.extraColumLayout.addWidget(self.extraContent)
        self.gridLayout_2.addWidget(self.extraRightBox, 1, 2, 1, 1)
        self.optionsFrame = QtWidgets.QFrame(self.centralwidget)
        self.optionsFrame.setStyleSheet("QWidget {\n"
"background: #222327\n"
"}\n"
"QPushButton {\n"
"background: none;\n"
"}")
        self.optionsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.optionsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.optionsFrame.setObjectName("optionsFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.optionsFrame)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.helpButton = QtWidgets.QPushButton(self.optionsFrame)
        self.helpButton.setStyleSheet("")
        self.helpButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-question-mark-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpButton.setIcon(icon1)
        self.helpButton.setIconSize(QtCore.QSize(30, 30))
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout_2.addWidget(self.helpButton)
        self.loginButton = QtWidgets.QPushButton(self.optionsFrame)
        self.loginButton.setStyleSheet("#loginButton {\n"
"background-color: #00a8f3;\n"
"padding: 5px;\n"
"border: 2px solid #00a8f3;\n"
"}\n"
"\n"
"#loginButton:pressed {\n"
"background-color: #2596be;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout_2.addWidget(self.loginButton)
        self.settingsButton = QtWidgets.QPushButton(self.optionsFrame)
        self.settingsButton.setStyleSheet("")
        self.settingsButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-settings-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon2)
        self.settingsButton.setIconSize(QtCore.QSize(20, 30))
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout_2.addWidget(self.settingsButton)
        self.gridLayout_2.addWidget(self.optionsFrame, 2, 0, 1, 3)
        self.titleFrame = QtWidgets.QFrame(self.centralwidget)
        self.titleFrame.setStyleSheet("background: #222327")
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QPushButton(self.titleFrame)
        self.logo.setText("")
        self.logo.setIcon(icon)
        self.logo.setIconSize(QtCore.QSize(30, 30))
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.softwareNameLabel = QtWidgets.QLabel(self.titleFrame)
        self.softwareNameLabel.setObjectName("softwareNameLabel")
        self.horizontalLayout.addWidget(self.softwareNameLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addWidget(self.titleFrame, 0, 0, 1, 3)
        self.extraLeftBox.raise_()
        self.extraRightBox.raise_()
        self.titleFrame.raise_()
        self.optionsFrame.raise_()
        self.contentFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hotkey TradingView"))
        self.helpText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<table border=\"1\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"0\" cellpadding=\"0\">\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">1 Day </span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">1 Day Chart</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">5 Min </span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">5 Min Chart</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">1 Min </span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">1 Min Chart</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">15 Min </span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">15 Min Chart</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">30 Min </span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">30 Min Chart</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">1 Hour </span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">1 Hour Chart</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">4 Hour </span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">4 Hour Chart</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">1 Week </span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">1 Week Chart</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Trend Line </span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Trendline</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Horz Line</span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Horzontal Line</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Open App </span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Open Trading View</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Auto</span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Auto Fit</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Hide</span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Hide Drawings</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Fib</span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Fib</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">2 X Square</span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:3; padding-right:3; padding-top:2; padding-bottom:2;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt;\">Square</span></p></td></tr></table></body></html>"))
        self.label_2.setText(_translate("MainWindow", "LICENSE KEY"))
        self.settingsLabel.setText(_translate("MainWindow", "Settings"))
        self.fibHotKeyInput.setText(_translate("MainWindow", "Alt+F"))
        self.hideDrawingsHotKeyInput.setText(_translate("MainWindow", "Ctrl+Alt+H"))
        self.label_5.setText(_translate("MainWindow", "Horizontal Line"))
        self.label_7.setText(_translate("MainWindow", "Hide Drawings"))
        self.label_3.setText(_translate("MainWindow", "Size of Square"))
        self.label.setText(_translate("MainWindow", "Wait Value"))
        self.horizontalLineHotKeyInput.setText(_translate("MainWindow", "Alt+H"))
        self.appNameInput.setText(_translate("MainWindow", "tradingview"))
        self.label_4.setText(_translate("MainWindow", "App Name"))
        self.trendLineHotKeyInput.setText(_translate("MainWindow", "Alt+T"))
        self.label_6.setText(_translate("MainWindow", "Trend Line"))
        self.label_8.setText(_translate("MainWindow", "Fib"))
        self.label_9.setText(_translate("MainWindow", "App Path"))
        self.updateButton.setText(_translate("MainWindow", "Save"))
        self.resetButton.setText(_translate("MainWindow", "Reset Settings"))
        self.loginButton.setText(_translate("MainWindow", "Log In"))
        self.softwareNameLabel.setText(_translate("MainWindow", "thinkorswim"))
from . import resources_rc
